### ISSUE TITLE
Add extra maintainers

### ISSUE THREAD

**Issue by IAlibay** [conda-forge/mdanalysis-sphinx-theme-feedstock#2]
### Comment:

Touch wood this is never truly needed, but it might be good to add some other mda coredevs are maintainers here (it's an exercise we really need to do for a bunch of upstream dependencies).

**Comment by lilyminium** [comment]
I could add all core devs to the team but that might create a lot of notifications. Are you happy being part of this team?

**Comment by IAlibay** [comment]
Yeah works for me, might want to maybe add Oliver too?

**Comment by lilyminium** [comment]
Done!
